name: testing
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  smart_arrays_base: ^2.1.0
  smart_signal_processing: ^2.1.1
  smart_arrays_numerics: ^2.1.1
  smart_arrays_dbstore: ^2.1.0
  smart_arrays_peaks: ^2.1.3
  scidart: ^0.0.1-dev.2
  


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
